# Generated by Django 3.0.2 on 2020-01-15 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacoes',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='avaliacoes',
            name='note',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
